### ISSUE TITLE
Deprecated alias...

### ISSUE THREAD

**Issue by joseffallman** [kverqus/hassam#3]
Såg detta i loggen. Har du koll på detta?

Logger: homeassistant.helpers.typing
Källa: helpers/deprecation.py:222
Inträffade först: 20:33:05 (1 händelser)
Senast loggade: 20:33:05

HomeAssistantType was used from hassam, this is a deprecated alias which will be removed in HA Core 2025.5. Use homeassistant.core.HomeAssistant instead, please report it to the author of the 'hassam' custom integration

**Comment by kverqus** [comment]
Det hade jag missat. Ser dock ut som att det bara är jag som varit slarvig och inte tagit bort en oanvänd import som pekade mot `homeassistant.helpers.typing`. Städar upp lite bland importerna (https://github.com/kverqus/hassam/commit/a3409f09279912405df5b04f80d4405cc994a959) och drar ut en ny version.
